-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 09:04:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `id_prov` INT NOT NULL,
  `ruc_prov` CHAR(11) NOT NULL,
  `nom_prov` VARCHAR(40) NOT NULL,
  `dir_prov` VARCHAR(40) NOT NULL,
  `tel_prov` VARCHAR(9) NOT NULL,
  `region` CHAR(1) NOT NULL,
  `correo_prov` VARCHAR(40) NOT NULL,
  `est_prov` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_prov`),
  UNIQUE INDEX `ruc_prov_UNIQUE` (`ruc_prov` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distritos` (
  `id_dis` INT NOT NULL,
  `nom_dis` VARCHAR(40) NOT NULL,
  `cod_postal` CHAR(5) NULL,
  PRIMARY KEY (`id_dis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cli` INT NOT NULL,
  `tip_doc` CHAR(10) NOT NULL,
  `nro_doc` CHAR(7) NOT NULL,
  `nom_cli` VARCHAR(40) NOT NULL,
  `ape_cli` VARCHAR(40) NOT NULL,
  `dir_cli` VARCHAR(40) NOT NULL,
  `id_dis` INT NOT NULL,
  `tel_cli` CHAR(9) NOT NULL,
  `correo_cli` VARCHAR(20) NOT NULL,
  `distritos_id_dis` INT NOT NULL,
  PRIMARY KEY (`id_cli`),
  INDEX `id_dis_idx` (`id_dis` ASC) VISIBLE,
  CONSTRAINT `id_dis`
    FOREIGN KEY (`id_dis`)
    REFERENCES `mydb`.`distritos` (`id_dis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas` (
  `id_area` INT NOT NULL,
  `nom_area` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargos` (
  `idcargos` INT NOT NULL,
  `nom_cargo` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idcargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id_cat` INT NOT NULL,
  `nom_cat` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategoria` (
  `id_subcat` INT NOT NULL,
  `nom_subcat` VARCHAR(40) NOT NULL,
  `id_cat` INT NULL,
  PRIMARY KEY (`id_subcat`),
  INDEX `id_cat_idx` (`id_cat` ASC) VISIBLE,
  CONSTRAINT `id_cat`
    FOREIGN KEY (`id_cat`)
    REFERENCES `mydb`.`categorias` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcas` (
  `idmarcas` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idmarcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`presentacion` (
  `id_pres` INT NOT NULL,
  `nom_pres` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_pres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_pro` INT NOT NULL,
  `nom_pro` VARCHAR(40) NOT NULL,
  `id_subcat` INT NULL,
  `id_marca` INT NULL,
  `id_pres` INT NULL,
  `stk_actual` INT NOT NULL,
  `stk_max` INT NOT NULL,
  `productoscol` VARCHAR(45) NULL,
  `img_pro` POLYGON NULL,
  `pre_pro` DECIMAL(7,2) NOT NULL,
  `ubi_pro` CHAR(6) NOT NULL,
  `est_pro` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_pro`),
  INDEX `id_subcat_idx` (`id_subcat` ASC) VISIBLE,
  INDEX `id_marca_idx` (`id_marca` ASC) VISIBLE,
  INDEX `id_pres_idx` (`id_pres` ASC) VISIBLE,
  CONSTRAINT `id_subcat`
    FOREIGN KEY (`id_subcat`)
    REFERENCES `mydb`.`subcategoria` (`id_subcat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`marcas` (`idmarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pres`
    FOREIGN KEY (`id_pres`)
    REFERENCES `mydb`.`presentacion` (`id_pres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleados` (
  `idempleados` INT NOT NULL,
  `nom_emp` VARCHAR(40) NOT NULL,
  `ape_emp` VARCHAR(40) NOT NULL,
  `dir_emp` VARCHAR(40) NOT NULL,
  `tel_emp` CHAR(9) NOT NULL,
  `id_car` INT NULL,
  `usu_emp` VARCHAR(12) NOT NULL,
  `pwd_emp` VARCHAR(12) NOT NULL,
  `est_emp` CHAR(1) NOT NULL,
  PRIMARY KEY (`idempleados`),
  INDEX `id_car_idx` (`id_car` ASC) VISIBLE,
  CONSTRAINT `id_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `mydb`.`cargos` (`idcargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaccion` (
  `id_tra` INT NOT NULL,
  `nom_tra` VARCHAR(50) NOT NULL,
  `tipo_tra` CHAR(1) NOT NULL,
  `estado` CHAR(1) NULL,
  PRIMARY KEY (`id_tra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motivos` (
  `id_mot` INT NOT NULL,
  `des_mot` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_mot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transportistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transportistas` (
  `id_trans` INT NOT NULL,
  `ruc_trans` CHAR(8) NOT NULL,
  `nom_trans` VARCHAR(25) NOT NULL,
  `nro_placa` CHAR(7) NOT NULL,
  `nro_lic` CHAR(7) NOT NULL,
  PRIMARY KEY (`id_trans`),
  UNIQUE INDEX `ruc_trans_UNIQUE` (`ruc_trans` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guias` (
  `id_guia` INT NOT NULL,
  `id_doc` INT NULL,
  `nro_doc` CHAR(7) NOT NULL,
  `fec_guia` DATE NOT NULL DEFAULT getdate(),
  `id_tra` INT NOT NULL,
  `id_emp` INT NOT NULL,
  `obser_guia` VARCHAR(350) NOT NULL,
  PRIMARY KEY (`id_guia`),
  INDEX `id_tra_idx` (`id_tra` ASC) VISIBLE,
  INDEX `id_emp_idx` (`id_emp` ASC) VISIBLE,
  CONSTRAINT `id_tra`
    FOREIGN KEY (`id_tra`)
    REFERENCES `mydb`.`transaccion` (`id_tra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_emp`
    FOREIGN KEY (`id_emp`)
    REFERENCES `mydb`.`empleados` (`idempleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guia_ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guia_ingreso` (
  `id_guia` INT NULL,
  `id_prov` INT NULL,
  `doc_ref` VARCHAR(30) NOT NULL,
  INDEX `id_prov_idx` (`id_prov` ASC) VISIBLE,
  CONSTRAINT `id_guia`
    FOREIGN KEY (`id_guia`)
    REFERENCES `mydb`.`guias` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prov`
    FOREIGN KEY (`id_prov`)
    REFERENCES `mydb`.`proveedores` (`id_prov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guia_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guia_salida` (
  `id_guia` INT NULL,
  `id_area` INT NULL,
  `doc_ref` VARCHAR(30) NOT NULL,
  INDEX `id_area_idx` (`id_area` ASC) VISIBLE,
  CONSTRAINT `id_guia`
    FOREIGN KEY (`id_guia`)
    REFERENCES `mydb`.`guias` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_area`
    FOREIGN KEY (`id_area`)
    REFERENCES `mydb`.`areas` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guia_remision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guia_remision` (
  `id_guia` INT NULL,
  `id_cliente` INT NULL,
  `pto_partida` VARCHAR(45) NOT NULL,
  `guia_remisioncol` VARCHAR(45) NOT NULL,
  `id_mot` INT NULL,
  `id_trans` INT NOT NULL,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_mot_idx` (`id_mot` ASC) VISIBLE,
  INDEX `id_trans_idx` (`id_trans` ASC) VISIBLE,
  CONSTRAINT `id_guia`
    FOREIGN KEY (`id_guia`)
    REFERENCES `mydb`.`guias` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_mot`
    FOREIGN KEY (`id_mot`)
    REFERENCES `mydb`.`motivos` (`id_mot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_trans`
    FOREIGN KEY (`id_trans`)
    REFERENCES `mydb`.`transportistas` (`id_trans`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_guia` (
  `id_det` INT NOT NULL,
  `id_guia` INT NULL,
  `id_pro` INT NULL,
  `can_pro` INT NOT NULL,
  `obs_pro` VARCHAR(300) NULL,
  `estado` CHAR(1) NULL,
  PRIMARY KEY (`id_det`),
  INDEX `id_pro_idx` (`id_pro` ASC) VISIBLE,
  INDEX `id_guia_idx` (`id_guia` ASC) VISIBLE,
  CONSTRAINT `id_pro`
    FOREIGN KEY (`id_pro`)
    REFERENCES `mydb`.`productos` (`id_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_guia`
    FOREIGN KEY (`id_guia`)
    REFERENCES `mydb`.`guias` (`id_guia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
